# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Python Ci

on:
  push:
    branches: 
       - main
  pull_request:
    branches: 
        - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      #Step 1 : cheack out the code from the repository
      - name: cheack out the code
        uses: actions/checkout@v2
        with:
          python-version: '3.8'
                
      #Step2 : Set up python environment
      - name: Set up python environment
        uses: actions/setup-python@v2

      #Step3 : Install dependencies
      - name: Install dependencies
        run: 
            python -m pip install --upgrade pip
             pip install -r requriment.txt

      #Step4 :Run Tests
      - name: Run Tests
        uses: pytest
